// <auto-generated />
using System;
using HealthTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319091509_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("HealthTracker.Models.HealthEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExerciseMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SleepHours")
                        .HasColumnType("REAL");

                    b.Property<double>("WaterLiters")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("HealthEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
